config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from puput import urls as puput_urls

from search import views as search_views
from home.sitemaps.views import sitemap
from multisite.views import robots

urlpatterns = [
    path('sitemap.xml', sitemap),
    path('robots.txt', robots),

    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(
        'cms/',
        include('admin_honeypot.urls', namespace='admin_honeypot_cms')),

    path('grappelli/', include('grappelli.urls')),
    path(settings.DJANGO_ADMIN_URL, admin.site.urls),
    path(settings.WAGTAIL_CMS_URL, include(wagtailadmin_urls)),

    path('documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    path('ajax-contact-forms/', include('ajax_contact_forms.urls')),

]

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:

    path("", include(puput_urls)),
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r"^pages/", include(wagtail_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wagtailwebsitebuilder/ajax_contact_forms/urls.py
from django.urls import path

from .api import ContactFormApi


app_name = 'ajax_contact_forms'
urlpatterns = [
    path('simple', ContactFormApi.as_view(), name='simple')
]

wagtailwebsitebuilder/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r"", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r"^pages/", include(wagtail_urls)),
]

wagtailwebsitebuilder/ajax_contact_forms/models.py
from django.db import models

from django_extensions.db.models import TimeStampedModel


class ContactForm(TimeStampedModel):
    sender_email = models.EmailField(blank=True)
    sender_name = models.CharField(max_length=250, blank=True)
    sender_message = models.CharField(max_length=250, blank=True)
    is_sender_notified = models.BooleanField(default=False, blank=True)
    is_admin_notified = models.BooleanField(default=False, blank=True)

    # the email info seen by admin
    from_email = models.EmailField()
    admin_emails = models.TextField()  # comma separated emails

    @property
    def admin_emails_as_list(self):
        emails = self.admin_emails.split(',')
        emails = [e.strip() for e in emails]
        return emails

wagtailwebsitebuilder/home/models.py
from django.db import models

from modelcluster.fields import ParentalKey
from wagtail.admin.edit_handlers import (
    FieldPanel, InlinePanel, StreamFieldPanel)
from wagtail.contrib.table_block.blocks import TableBlock
from wagtail.contrib.sitemaps.sitemap_generator import Sitemap
from wagtail.core import blocks
from wagtail.core.fields import StreamField
from wagtail.core.models import Page, Orderable
from wagtail.images.blocks import ImageChooserBlock
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.models import register_snippet
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtailmetadata.models import MetadataPageMixin
from wagtailschemaorg.models import PageLDMixin

from .db import CSSMixin, WebContentSchemaMixin
from .blocks import (
    HeroBlock, CustomRichTextBlock, TileStreamBlock, ColumnsBlock, CardBlock,
    SchemaPersonBlock, SchemaProductBlock)
from .helpers import TocBlock, CustomImageBlock
from puputextension.helpers import CodeBlock


@register_snippet
class NavBarItem(models.Model):
    link = models.CharField(max_length=250, blank=True, default='#')
    text = models.CharField(max_length=50, blank=True)

    panels = [
        FieldPanel('link'),
        FieldPanel('text'),
    ]

    def __str__(self):
        return self.text


class HomePageNavBarItem(Orderable, models.Model):
    page = ParentalKey(
        'home.HomePage',
        on_delete=models.CASCADE,
        related_name='navbar_items')
    navbar_item = models.ForeignKey(
        'home.NavBarItem',
        on_delete=models.CASCADE,
        related_name='in_home_pages')

    panels = [
        SnippetChooserPanel('navbar_item')
    ]


class HomePage(
        WebContentSchemaMixin, PageLDMixin, CSSMixin, MetadataPageMixin, Page):
    hero = StreamField([
        ('hero', HeroBlock()),
    ], null=True, blank=True)
    body = StreamField([
        ('card', CardBlock()),
        ('code', CodeBlock()),
        ('columns', ColumnsBlock()),
        ('custom_image', CustomImageBlock()),
        ('custom_paragraph', CustomRichTextBlock()),
        ('html', blocks.RawHTMLBlock()),
        ('image', ImageChooserBlock()),
        ('paragraph', blocks.RichTextBlock()),
        ('schema_product', SchemaProductBlock()),
        ('schema_person', SchemaPersonBlock()),
        ('table', TableBlock(table_options={
            'minSpareRows': 0,
            'startRows': 3,
            'startCols': 3,
            'contextMenu': [
                'row_above',
                'row_below',
                '---------',
                'col_left',
                'col_right',
                '---------',
                'remove_row',
                'remove_col',
                '---------',
                'undo',
                'redo',
                '---------',
                'copy',
                'cut'
                '---------',
                'alignment',
            ],
        })),
        ('tile', TileStreamBlock()),
        ('toc', TocBlock()),
        ('with_id', blocks.StructBlock(
            [
                ('id', blocks.CharBlock()),
                ('paragraph', blocks.RichTextBlock()),
            ],
            template='home/blocks/with_id.html'
        )),
    ])
    navbar_icon = models.ForeignKey(
        'wagtailimages.Image',
        on_delete=models.SET_NULL,
        related_name='+',
        null=True)
    css = models.FileField(
        upload_to='css/home/',
        null=True,
        blank=True)

    content_panels = Page.content_panels + [
        ImageChooserPanel('navbar_icon'),
        InlinePanel('navbar_items', label='Navbar Items'),
        FieldPanel('css', classname='full'),
        StreamFieldPanel('hero', classname='full'),
        StreamFieldPanel('body', classname='full'),
    ]

    og_type = 'website'

    promote_panels = MetadataPageMixin.promote_panels


class SitemapPage(WebContentSchemaMixin, PageLDMixin, MetadataPageMixin, Page):
    hero = StreamField([
        ('hero', HeroBlock()),
    ], null=True, blank=True)
    body = StreamField([
        ('custom_paragraph', CustomRichTextBlock()),
        ('html', blocks.RawHTMLBlock()),
    ])
    navbar_icon = models.ForeignKey(
        'wagtailimages.Image',
        on_delete=models.SET_NULL,
        related_name='+',
        null=True)

    content_panels = Page.content_panels + [
        ImageChooserPanel('navbar_icon'),
        StreamFieldPanel('hero', classname='full'),
        StreamFieldPanel('body', classname='full'),
    ]

    og_type = 'article'

    promote_panels = MetadataPageMixin.promote_panels

    def get_context(self, request):
        context = super().get_context(request)
        context['root_page'] = Sitemap(request).items().first()
        return context

wagtailwebsitebuilder/ajax_contact_forms/forms.py
from django import forms
from django.conf import settings
from django.core.mail import EmailMessage

from .models import ContactForm


def get_admin_emails_as_flat_list():
    emails = settings.ADMINS
    emails = [email for name, email in emails]
    return emails


class ContactFormModelForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = [
            'sender_email',
            'sender_name',
            'sender_message',
        ]

    def is_valid(self):
        """Set from_email and admin_emails then proceed"""
        from_email = 'webmaster@xofytech.com'  # TODO
        self.instance.from_email = from_email

        emails = get_admin_emails_as_flat_list()
        emails = ','.join(emails)  # transform to comma separated strings
        self.instance.admin_emails = emails

        is_valid = super().is_valid()
        return is_valid

    def save(self, commit=False):
        """Send email to admin then save"""
        mail_result = self.send_email()
        if mail_result:
            self.instance.is_admin_notified = True

        contact = super().save(commit=commit)

        return contact

    def send_email(self):
        # mail content
        contact = self.instance
        email = contact.sender_email
        name = contact.sender_name
        message = contact.sender_message
        message = '\
            Name: {}\
            Email: {}\
            Message: {}\
            '.format(name, email, message)
        subject = 'Contact Form'
        recipient_list = contact.admin_emails_as_list

        email = EmailMessage(
            subject=subject,
            body=message,
            from_email=contact.from_email,
            to=recipient_list,
        )

        return email.send(fail_silently=True)

wagtailwebsitebuilder/system/forms.py
from django import forms

from wagtail.users.forms import UserEditForm

from .models import UserProfile


class CustomUserEditForm(UserEditForm):
    twitter_handle = forms.CharField(required=False)
    facebook_url = forms.URLField(required=False)
    linkedin_url = forms.URLField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if hasattr(self.instance, 'custom_profile'):
            profile = self.instance.custom_profile
            self.fields['twitter_handle'].initial = profile.twitter_handle
            self.fields['facebook_url'].initial = profile.facebook_url
            self.fields['linkedin_url'].initial = profile.linkedin_url
        else:
            UserProfile.objects.create(user=self.instance)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.custom_profile.twitter_handle = self.cleaned_data[
            'twitter_handle']
        user.custom_profile.facebook_url = self.cleaned_data[
            'facebook_url']
        user.custom_profile.linkedin_url = self.cleaned_data[
            'linkedin_url']

        if self.password_enabled:
            password = self.cleaned_data['password1']
            if password:
                user.set_password(password)

        if commit:
            user.save()
            self.save_m2m()
        return user

wagtailwebsitebuilder/ajax_contact_forms/views.py
from django.http import JsonResponse
from django.views.generic.edit import CreateView

from .forms import ContactForm as Contact, ContactFormModelForm


class ContactFormCreateView(CreateView):
    model = Contact
    form_class = ContactFormModelForm
    http_method_names = ['post']

    def get_success_url(self):
        url = self.request.META.get('HTTP_REFERER', None) or '/'
        return url

    def form_invalid(self, form):
        ajax = self.request.is_ajax()
        raise Exception
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)

        return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'ok': True
            }
            return JsonResponse(data)

        return response

wagtailwebsitebuilder/home/sitemaps/views.py
import inspect
from django.contrib.sitemaps import (
    views as sitemap_views, Sitemap as DjangoSitemap)


class Sitemap(DjangoSitemap):

    def __init__(self, request=None):
        self.request = request

    def location(self, obj):
        return obj.get_full_url(self.request)

    def lastmod(self, obj):
        # fall back on latest_revision_created_at if last_published_at is null
        # (for backwards compatibility from before last_published_at was added)
        last_mod = obj.last_published_at or obj.latest_revision_created_at
        last_mod = last_mod.strftime('%Y-%m-%dT%H:%M:%S%z')
        return last_mod

    def get_wagtail_site(self):
        site = getattr(self.request, 'site', None)
        if site is None:
            from wagtail.core.models import Site
            return Site.objects.select_related(
                'root_page'
            ).get(is_default_site=True)
        return site

    def items(self):
        return (
            self.get_wagtail_site()
            .root_page
            .get_descendants(inclusive=True)
            .live()
            .public()
            .order_by('path')
            .specific())

    def _urls(self, page, protocol, domain):
        urls = []
        last_mods = set()

        for item in self.paginator.page(page).object_list:

            url_info_items = item.get_sitemap_urls(self.request)

            for url_info in url_info_items:
                urls.append(url_info)
                last_mods.add(url_info.get('lastmod'))

        # last_mods might be empty if the whole site is private
        if last_mods and None not in last_mods:
            self.latest_lastmod = max(last_mods)
        return urls


def index(request, sitemaps, **kwargs):
    sitemaps = prepare_sitemaps(request, sitemaps)
    return sitemap_views.index(request, sitemaps, **kwargs)


def sitemap(request, sitemaps=None, **kwargs):
    if sitemaps:
        sitemaps = prepare_sitemaps(request, sitemaps)
    else:
        sitemaps = {'wagtail': Sitemap(request)}
    return sitemap_views.sitemap(request, sitemaps, **kwargs)


def prepare_sitemaps(request, sitemaps):
    """Intialize the wagtail Sitemap by passing the request.site value. """
    initialised_sitemaps = {}
    for name, sitemap_cls in sitemaps.items():
        if inspect.isclass(sitemap_cls) and issubclass(sitemap_cls, Sitemap):
            initialised_sitemaps[name] = sitemap_cls(request)
        else:
            initialised_sitemaps[name] = sitemap_cls
    return initialised_sitemaps

wagtailwebsitebuilder/multisite/views.py
import os

from django.conf import settings
from django.http import FileResponse

from .models import SeoSettings


def robots(request):
    robots_text = SeoSettings.for_site(request.site).robots_txt

    if robots_text:
        return FileResponse(robots_text.file)
    else:
        filename = os.path.join(settings.MEDIA_ROOT, 'robots.txt')
        if not os.path.isfile(filename):
            with open(filename, 'w') as fp:
                default = """User-agent: *
Disallow: /cms/
Disallow: /admin/"""
                fp.write(default)
        return FileResponse(open(filename, 'rb'))

wagtailwebsitebuilder/search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render

from wagtail.core.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return render(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

wagtailwebsitebuilder/tutorials/views.py
from django.shortcuts import render

# Create your views here.

wagtailwebsitebuilder/templates/home/home_page.html
{% extends "base.html" %}
{% load static wagtailcore_tags wagtailimages_tags compress sekizai_tags wagtailschemaorg_tags wagtailmetadata_tags %}

{% block body_class %}template-homepage{% endblock %}


{% block other_metas %}
    {% meta_tags %}
    <link rel="canonical" href="{{ page.get_url }}"/>
{% endblock %}

{% block global_css %}

  {% addtoblock 'css' %}
    <link rel="preload" as="style" href="{% static 'css/code.css' %}" onload="this.onload=null;this.rel='stylesheet'">     
    <noscript><link rel="stylesheet" href="{% static 'css/code.css' %}"></noscript>
  {% endaddtoblock %}

  {% addtoblock 'css' %}
    {% with primary=settings.multisite.SiteBranding.primary_color secondary=settings.multisite.SiteBranding.secondary_color accent=settings.multisite.SiteBranding.accent_color accent_2=settings.multisite.SiteBranding.accent_2_color %}
      <style>
        .site-background-primary { background-color: {{ primary }} !important; }
        .site-text-secondary { color: {{ secondary }} !important; }
      </style>
    {% endwith %}
  {% endaddtoblock %}

  {% addtoblock 'css' %}
    {% if page.css_url %}
        <link rel="preload" as="style" href="{{ page.css_url }}" onload="this.onload=null;this.rel='stylesheet'">     
        <noscript><link rel="stylesheet" href="{{ page.css_url }}"></noscript>
    {% else %}
      {{ block.super }}
    {% endif %}
  {% endaddtoblock %}
{% endblock global_css %}

{% block base_content %}

  <header>
    <nav id="navBar" class="navbar is-fixed-top has-background-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="#">
          {% image settings.multisite.SiteBranding.nav_icon fill-112x28 %}
        </a>

        <a
          :class="{ 'navbar-burger burger': true, 'is-active': burgerIsActive}"
          @click="toggleBurger"
          role="button"
          aria-label="menu"
          aria-expanded="false"
          data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div
        id="navbarBasicExample"
        :class="{ 'navbar-menu has-background-primary': true, 'is-active': burgerIsActive}">

        <div class="navbar-end">
          {% for navbar_item in page.navbar_items.all %}
            <a class="navbar-item" href="{{ navbar_item.navbar_item.link }}" @click="toggleBurger">
              {{ navbar_item.navbar_item.text}}
            </a>
          {% endfor %}
        </div>
      </div>
    </nav>
  </header>

  <main class="content">
    {% include_block page.hero  %}

    <section class="section">
      <div class="container">
        {% include_block page.body  %}
      </div>
      <div class="container">
        <form id="contactForm" class="form" action="{% url 'ajax_contact_forms:simple' %}" method="POST" @submit.prevent="sendContactForm">
            {% csrf_token %}

            <div class="field">
              <label class="label">Message</label>
              <div class="control">
                <textarea class="textarea" v-model="message" required placeholder="Message" :disabled="!enableSending"></textarea>
              </div>
            </div>

            <div class="field">
              <label class="label">Email Address</label>
              <div class="control">
                <input class="input" type="email" v-model="emailAddress" required placeholder="john@domain.com" :disabled="!enableSending">
              </div>
            </div>

            <div class="field">
              <label class="label">Name</label>
              <div class="control">
                <input class="input" type="text" v-model="name" placeholder="Your name is optional" :disabled="!enableSending">
              </div>
            </div>

            <div class="field">
              <label class="label">asfasfaswqr<span class="has-text-link">[[ randomWord ]]</span>wrasdfasfd</label>
              <div class="control">
                <input :class="{'input': true, 'is-danger': showRecaptchaHelp }" type="text" ref="customCaptcha" v-model="customCaptcha" placeholder="Highlighted word" :required="showRecaptchaHelp">
              </div>
              <p
                :class="{'help': true, 'is-danger': showRecaptchaHelp }"
                v-show="showRecaptchaHelp">Help X of Y prevent spams. Thank you for your understanding <3.</p>
            </div>

            <div class="field">
              <div class="control">
                <button class="button has-background-link is-fullwidth" :disabled="!enableSending">Submit</button>
              </div>
            </div>

            <modal-card
              :message="'Your message has been sent'"
              :title="'Thank you!'"
              :show-modal="showThankYouModal"
              @close-modal="closeModal"></modal-card>
        </form>
      </div>
    </section>
  </main>

  {% addtoblock "js_first" %}
    {% if debug %}
      <script src="{% static 'vendor/vue/vue.js' %}" defer></script>
    {% else %}
      <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.min.js" defer></script>
    {% endif %}
  {% endaddtoblock %}

  {% addtoblock "js" %}
    {% if debug %}
      <script src="{% static 'vendor/axios.min.js' %}" defer></script>
    {% else %}
      <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js" defer></script>
    {% endif %}
  {% endaddtoblock %}

  {% addtoblock "js" %}
      <script src="{% static "home/navBarApp.js" %}" defer></script>
  {% endaddtoblock %}

  {% addtoblock "js" %}
      <script src="{% static "js/toc.js" %}" defer></script>
  {% endaddtoblock %}

  {% addtoblock "js" %}
      <script src="{% static "home/componentModal.js" %}" defer></script>
  {% endaddtoblock %}

  {% addtoblock "js" %}
      <script src="{% static "ajax_contact_forms/contactFormApp.js" %}" defer></script>
  {% endaddtoblock %}

  {% addtoblock "js" %}
      <script src="{% static 'js/lazyLoader.js' %}" defer></script>
  {% endaddtoblock %}

  {% ld_for_object %}
{% endblock base_content %}

wagtailwebsitebuilder/templates/home/sitemap_page.html
{% extends "base.html" %}
{% load static wagtailcore_tags wagtailimages_tags compress sekizai_tags wagtailschemaorg_tags wagtailmetadata_tags %}

{% block body_class %}template-homepage{% endblock %}


{% block other_metas %}
    {% meta_tags %}
    <link rel="canonical" href="{{ page.get_url }}"/>
{% endblock %}

{% block global_css %}

  {% addtoblock 'css' %}
    {% with primary=settings.multisite.SiteBranding.primary_color secondary=settings.multisite.SiteBranding.secondary_color accent=settings.multisite.SiteBranding.accent_color accent_2=settings.multisite.SiteBranding.accent_2_color %}
      <style>
        .site-background-primary { background-color: {{ primary }} !important; }
        .site-text-secondary { color: {{ secondary }} !important; }
      </style>
    {% endwith %}
  {% endaddtoblock %}

  {% addtoblock 'css' %}
    {% if page.css_url %}
        <link rel="stylesheet" type="text/css" href="{{ page.css_url }}">
    {% else %}
      {{ block.super }}
    {% endif %}
  {% endaddtoblock %}
{% endblock global_css %}


{% block base_content %}

  <header>
    <nav id="navBar" class="navbar is-fixed-top has-background-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="#">
          {% image settings.multisite.SiteBranding.nav_icon fill-112x28 %}
        </a>

        <a
          :class="{ 'navbar-burger burger': true, 'is-active': burgerIsActive}"
          @click="toggleBurger"
          role="button"
          aria-label="menu"
          aria-expanded="false"
          data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div
        id="navbarBasicExample"
        :class="{ 'navbar-menu has-background-primary': true, 'is-active': burgerIsActive}">

        <div class="navbar-end">
          {% for navbar_item in page.navbar_items.all %}
            <a class="navbar-item" href="{{ navbar_item.navbar_item.link }}" @click="toggleBurger">
              {{ navbar_item.navbar_item.text}}
            </a>
          {% endfor %}
        </div>
      </div>
    </nav>
  </header>

  <main class="content">
    {% include_block page.hero  %}

    <section class="section" style="min-height: 100vh;">
      <div class="container is-full-height">
        <div class="columns is-full-height is-vcentered">
          <div class="column">
            <nav class="menu">
              <p class="menu-label"><a href="/">Home</a></p>
              <ul class="menu-list">
                {% for child_level_1 in root_page.get_children %}
                    <li><a href="{{ child_level_1.get_url }}">{{ child_level_1.title }}</a></li>
                    {% with child_level_1.get_children as children_2 %}
                        {% if children_2 %}
                          <ul>
                            {% for child_level_2 in children_2 %}
                                <li><a href="{{ child_level_2.get_url }}">{{ child_level_2.title }}</a></li>
                            {% endfor %}
                          </ul>
                        {% endif %}
                    {% endwith %}
                {% endfor %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
        {% include_block page.body  %}
      </div>
    </section>
  </main>

  {% addtoblock "js_first" %}
    {% if debug %}
      <script src="{% static 'vendor/vue/vue.js' %}" defer></script>
    {% else %}
      <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.min.js" defer></script>
    {% endif %}
  {% endaddtoblock %}

  {% addtoblock "js" %}
      <script src="{% static "home/navBarApp.js" %}" defer></script>
  {% endaddtoblock %}

  {% addtoblock "js" %}
      <script src="{% static 'js/lazyLoader.js' %}" defer></script>
  {% endaddtoblock %}

  {% ld_for_object %}
{% endblock base_content %}